version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge
